import type { Workshop } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

export const workshops: Workshop[] = [
  {
    id: '1',
    name: 'Precision Auto Works',
    address: '123 Main St',
    city: 'Metropolis',
    rating: 4.8,
    reviewCount: 152,
    hasObdiiScanner: true,
    services: ['Engine Repair', 'OBD-II Scan', 'Oil Change', 'Brake Service'],
    image: PlaceHolderImages.find(img => img.id === 'workshop-1')!,
  },
  {
    id: '2',
    name: 'Dynamic Drivetrains',
    address: '456 Oak Ave',
    city: 'Metropolis',
    rating: 4.5,
    reviewCount: 89,
    hasObdiiScanner: false,
    services: ['Transmission', 'Oil Change', 'Tire Rotation'],
    image: PlaceHolderImages.find(img => img.id === 'workshop-2')!,
  },
  {
    id: '3',
    name: 'Speedy Scan & Repair',
    address: '789 Pine Ln',
    city: 'Metropolis',
    rating: 4.9,
    reviewCount: 230,
    hasObdiiScanner: true,
    services: ['OBD-II Diagnostics', 'ECU Flashing', 'Performance Tuning'],
    image: PlaceHolderImages.find(img => img.id === 'workshop-3')!,
  },
  {
    id: '4',
    name: 'Reliable Rides',
    address: '101 Maple Dr',
    city: 'Metropolis',
    rating: 4.6,
    reviewCount: 110,
    hasObdiiScanner: true,
    services: ['General Maintenance', 'OBD-II Scan', 'Suspension'],
    image: PlaceHolderImages.find(img => img.id === 'workshop-4')!,
  },
  {
    id: '5',
    name: "Old Bill's Garage",
    address: '212 Birch Rd',
    city: 'Metropolis',
    rating: 4.3,
    reviewCount: 65,
    hasObdiiScanner: false,
    services: ['Classic Cars', 'Carburetors', 'Body Work'],
    image: PlaceHolderImages.find(img => img.id === 'workshop-5')!,
  },
  {
    id: '6',
    name: 'Tech-Forward Auto',
    address: '333 Cedar Blvd',
    city: 'Metropolis',
    rating: 4.7,
    reviewCount: 95,
    hasObdiiScanner: true,
    services: ['EV Repair', 'Hybrid Service', 'Advanced Diagnostics'],
    image: PlaceHolderImages.find(img => img.id === 'workshop-6')!,
  },
];
